import os
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List

from src.database import get_db
from src.models import BlacklistedIP, User
from src.schemas import BlacklistCreate, BlacklistResponse, normalize_blacklist_address
from src.core.logger import logger
from src.core.security import get_current_user
from src.core.queue import redis_client

router = APIRouter(prefix="/defense", tags=["Defense Operations"])
BLACKLIST_CONFIG_PATH = Path(os.getenv("NGINX_BLOCKED_IPS_CONF", "/etc/nginx/generated/blocked-ips.conf"))


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(f"{path.suffix}.tmp")
    tmp_path.write_text(content, encoding="utf-8")
    os.replace(tmp_path, path)


async def sync_nginx_blacklist(db: AsyncSession) -> None:
    result = await db.execute(select(BlacklistedIP.ip_address).order_by(BlacklistedIP.ip_address))
    ips = sorted(dict.fromkeys(row[0] for row in result.all()))
    lines = [
        "# Generated by W-IDS Defense. Included inside protected-site locations.\n",
        "# Nginx reload-watch validates and reloads this file automatically.\n",
    ]
    for ip in ips:
        lines.append(f"deny {ip};\n")
    lines.append("allow all;\n")
    atomic_write(BLACKLIST_CONFIG_PATH, "".join(lines))
    logger.info("Nginx blacklist synced path=%s entries=%s", BLACKLIST_CONFIG_PATH, len(ips))

@router.get("/blacklist", response_model=List[BlacklistResponse])
async def get_blacklist(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Fetches the list of currently blacklisted IPs for the workspace."""
    result = await db.execute(
        select(BlacklistedIP).where(
            BlacklistedIP.workspace_id == current_user.workspace_id
        ).order_by(BlacklistedIP.timestamp.desc())
    )
    return result.scalars().all()

@router.post("/blacklist", response_model=BlacklistResponse, status_code=status.HTTP_201_CREATED)
async def add_to_blacklist(
    data: BlacklistCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Adds a malicious IP to the workspace blacklist and syncs with Redis cache."""
    # Check if already blacklisted
    result = await db.execute(
        select(BlacklistedIP).where(
            BlacklistedIP.ip_address == data.ip_address,
            BlacklistedIP.workspace_id == current_user.workspace_id
        )
    )
    if result.scalars().first():
        raise HTTPException(status_code=400, detail="IP is already blacklisted.")

    # Save to Database
    new_ban = BlacklistedIP(
        ip_address=data.ip_address,
        reason=data.reason,
        created_by=current_user.id,
        workspace_id=current_user.workspace_id
    )
    db.add(new_ban)
    await db.commit()
    await db.refresh(new_ban)

    # Sync with Redis for ultra-fast sensor blocking
    redis_key = f"blacklist:workspace:{current_user.workspace_id}"
    await redis_client.sadd(redis_key, data.ip_address)
    await sync_nginx_blacklist(db)

    return new_ban

@router.delete("/blacklist/{ip_address:path}", status_code=status.HTTP_204_NO_CONTENT)
async def remove_from_blacklist(
    ip_address: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Removes an IP from the workspace blacklist (Release)."""
    try:
        normalized_ip = normalize_blacklist_address(ip_address)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    result = await db.execute(
        select(BlacklistedIP).where(
            BlacklistedIP.ip_address == normalized_ip,
            BlacklistedIP.workspace_id == current_user.workspace_id
        )
    )
    banned_ip = result.scalars().first()
    
    if not banned_ip:
        raise HTTPException(status_code=404, detail="IP not found in blacklist.")

    # Remove from Database
    await db.delete(banned_ip)
    await db.commit()

    # Remove from Redis Cache
    redis_key = f"blacklist:workspace:{current_user.workspace_id}"
    await redis_client.srem(redis_key, normalized_ip)
    await sync_nginx_blacklist(db)

    return None
