"""Remove subscription plan

Revision ID: 43479816f381
Revises: 69f7ff410b76
Create Date: 2026-04-08 12:27:50.428818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43479816f381'
down_revision: Union[str, Sequence[str], None] = '69f7ff410b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'subscription_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('subscription_plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
