"""Add notes to alerts

Revision ID: 69f7ff410b76
Revises: bf3c5efa1158
Create Date: 2026-04-07 11:47:26.364052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f7ff410b76'
down_revision: Union[str, Sequence[str], None] = 'bf3c5efa1158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'notes')
    # ### end Alembic commands ###
