"""Add MonitoredWebsite

Revision ID: a0b7854b7942
Revises: f858ca31c698
Create Date: 2026-05-09 23:00:54.377747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b7854b7942'
down_revision: Union[str, Sequence[str], None] = 'f858ca31c698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('target_ip', sa.String(), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_websites_domain'), 'monitored_websites', ['domain'], unique=False)
    op.create_index(op.f('ix_monitored_websites_id'), 'monitored_websites', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_websites_workspace_id'), 'monitored_websites', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_websites_workspace_id'), table_name='monitored_websites')
    op.drop_index(op.f('ix_monitored_websites_id'), table_name='monitored_websites')
    op.drop_index(op.f('ix_monitored_websites_domain'), table_name='monitored_websites')
    op.drop_table('monitored_websites')
    # ### end Alembic commands ###
