"""add_pro_features_to_alerts_and_blacklist

Revision ID: c6c1a6e0ca4e
Revises: f13023afd2b9
Create Date: 2026-04-14 11:00:45.395768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6c1a6e0ca4e'
down_revision: Union[str, Sequence[str], None] = 'f13023afd2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_ips', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('blacklisted_ips_created_by_fkey'), 'blacklisted_ips', type_='foreignkey')
    op.drop_column('blacklisted_ips', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_ips', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('blacklisted_ips_created_by_fkey'), 'blacklisted_ips', 'users', ['created_by'], ['id'])
    op.drop_column('blacklisted_ips', 'timestamp')
    # ### end Alembic commands ###
