"""add_blacklist_table

Revision ID: f13023afd2b9
Revises: 43479816f381
Create Date: 2026-04-13 07:56:28.237499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13023afd2b9'
down_revision: Union[str, Sequence[str], None] = '43479816f381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_ips_id'), 'blacklisted_ips', ['id'], unique=False)
    op.create_index(op.f('ix_blacklisted_ips_ip_address'), 'blacklisted_ips', ['ip_address'], unique=False)
    op.create_index(op.f('ix_blacklisted_ips_workspace_id'), 'blacklisted_ips', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_ips_workspace_id'), table_name='blacklisted_ips')
    op.drop_index(op.f('ix_blacklisted_ips_ip_address'), table_name='blacklisted_ips')
    op.drop_index(op.f('ix_blacklisted_ips_id'), table_name='blacklisted_ips')
    op.drop_table('blacklisted_ips')
    # ### end Alembic commands ###
