"""add_unique_to_blacklist

Revision ID: f3acdf067d46
Revises: d1f4c7b8e9a2
Create Date: 2026-04-28 12:38:08.440332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3acdf067d46'
down_revision: Union[str, Sequence[str], None] = 'd1f4c7b8e9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blacklisted_ips_ip_address', table_name='blacklisted_ips')
    op.create_index(op.f('ix_blacklisted_ips_ip_address'), 'blacklisted_ips', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_ips_ip_address'), table_name='blacklisted_ips')
    op.create_index('ix_blacklisted_ips_ip_address', 'blacklisted_ips', ['ip_address'], unique=False)
    # ### end Alembic commands ###
